# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r:
  - release

r_github_packages: ukgovdatascience/govdown

# Make bash scripts executable, so they can be run later.
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh

script:
- "./_build.sh"
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./_deploy.sh; else echo "PR so
  not deploying"; fi

before_install:
- openssl aes-256-cbc -K $encrypted_e5387e4e26d8_key -iv $encrypted_e5387e4e26d8_iv
  -in deploy_key.enc -out deploy_key -d
